// <auto-generated />
using IESPeñasNegras.ProyectoEjemplo.Consola;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace consola.Migrations
{
    [DbContext(typeof(VehiculosContext))]
    [Migration("20220330120358_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CapacidadDeCarga")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Camiones");
                });

            modelBuilder.Entity("IESPeñasNegras.ProyectoEjemplo.Consola.Vehiculos.Rueda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Diametro")
                        .HasColumnType("int");

                    b.Property<int>("TurismoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurismoId");

                    b.ToTable("Ruedas");
                });

            modelBuilder.Entity("IESPeñasNegras.ProyectoEjemplo.Consola.Vehiculos.Turismo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Turismos");
                });

            modelBuilder.Entity("IESPeñasNegras.ProyectoEjemplo.Consola.Vehiculos.Rueda", b =>
                {
                    b.HasOne("IESPeñasNegras.ProyectoEjemplo.Consola.Vehiculos.Turismo", "Turismo")
                        .WithMany("Ruedas")
                        .HasForeignKey("TurismoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
